### ISSUE TITLE
Adicionar licença livre

### ISSUE THREAD

**Issue by pizzamaker** [ops-org/fiscalize-android#1]
Faltou especificar uma licença livre para o projeto, preferencialmente em um arquivo LICENSE.md. Pessoalmente, sugiro AGPLv3 :)

**Comment by danilo-favoratti** [comment]
Tem razão, estou um pouco afastado do projeto. Não gostaria de nos ajudar com isso?

E, se não for abusar, quero uma de calabresa também! :)

Grande abraço
